import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { GlassCard } from "@/components/ui-kit";
import { Button } from "@/components/ui/button";
import { Copy, Download, Printer } from "lucide-react";

export const Route = createFileRoute("/reports/executive")({
  head: () => ({
    meta: [
      { title: "Executive Summary · Kochi | Project Sentinel" },
      { name: "description", content: "Executive summary of Kochi city operations: traffic, emergencies, flood risk and AI recommendations." },
      { property: "og:title", content: "Executive Summary · Kochi" },
      { property: "og:description", content: "A daily executive report on Kochi city operations." },
    ],
  }),
  component: ExecutiveReport,
});

function ExecutiveReport() {
  const today = new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" });

  const copyMarkdown = () => {
    const md = `# Kochi Executive Summary — ${today}\n\nPrepared by Project Sentinel.\n\n## Traffic Overview\nHeavy congestion at Vytilla and Edappally corridors. City-wide flow index 62/100.\n\n## Emergency Summary\n2 critical incidents active (Kundannoor accident, NH-66 container truck). Both dispatched.\n\n## Flood Risk\nMarine Drive corridor at 62% saturation. Pumps on standby.\n\n## AI Recommendations\n- Reroute NH-66 southbound via Palarivattom bypass\n- Add 4 buses on Vytilla ↔ Kakkanad\n- Pre-position 2 rescue units at Marine Drive walkway\n`;
    navigator.clipboard.writeText(md);
  };

  return (
    <AppShell>
      <div className="space-y-6">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div>
            <p className="text-xs uppercase tracking-widest text-muted-foreground">Analyze · 05.b</p>
            <h1 className="font-display text-3xl font-semibold tracking-tight">Executive Summary</h1>
            <p className="mt-1 text-sm text-muted-foreground">Daily briefing for city leadership. Auto-generated by Sentinel.</p>
          </div>
          <div className="flex gap-2 print:hidden">
            <Button variant="outline" size="sm" className="gap-1.5" onClick={copyMarkdown}>
              <Copy className="size-3.5" /> Copy markdown
            </Button>
            <Button variant="outline" size="sm" className="gap-1.5" onClick={() => window.print()}>
              <Printer className="size-3.5" /> Print
            </Button>
            <Button size="sm" className="gap-1.5" onClick={() => window.print()}>
              <Download className="size-3.5" /> Export PDF
            </Button>
          </div>
        </div>

        <div className="mx-auto max-w-3xl">
          <GlassCard className="!p-10">
            <div className="border-b border-border pb-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-muted-foreground">
                    Kochi Municipal · Command Report
                  </p>
                  <h2 className="mt-1 font-display text-2xl font-semibold">Daily Executive Summary</h2>
                </div>
                <div className="text-right">
                  <p className="text-xs text-muted-foreground">{today}</p>
                  <p className="text-[10px] uppercase tracking-widest text-muted-foreground">Prepared by Sentinel AI</p>
                </div>
              </div>
            </div>

            <Section title="Traffic Overview">
              <p>
                Heavy congestion recorded at <b>Vytilla Junction</b> (+48% vs baseline) and <b>Edappally NH-66</b> (+62%).
                City-wide flow index sits at <b>62/100</b>. Sentinel rerouted <b>1,240 vehicles</b> during peak hours; average commute
                time reduced by <b>7 minutes</b>.
              </p>
            </Section>

            <Section title="Emergency Summary">
              <ul className="ml-5 list-disc space-y-1">
                <li>Multi-vehicle collision at Kundannoor — Ambulance K-14 dispatched, green corridor active.</li>
                <li>Container truck overturned NH-66 Edappally — Fire unit F-3 en route, lanes 2-3 closed.</li>
                <li>All 4 medium/low incidents assigned to responsible departments within 3 minutes.</li>
              </ul>
            </Section>

            <Section title="Flood Risk">
              <p>
                Marine Drive corridor at <b>62%</b> catchment saturation. Sentinel recommends closing the north lane by 6:30 PM.
                Two rescue units pre-positioned. Kaloor and MG Road elevated to watch level.
              </p>
            </Section>

            <Section title="AI Recommendations">
              <ul className="ml-5 list-disc space-y-1">
                <li>Reroute NH-66 southbound via Palarivattom bypass through peak evening.</li>
                <li>Add 4 buses on Vytilla ↔ Kakkanad; increase Blue-line metro frequency to 4 min.</li>
                <li>Push citizen advisory for Marine Drive corridor now.</li>
                <li>Approve overtime for 12 traffic officers at Vytilla + Aluva stations.</li>
              </ul>
            </Section>

            <div className="mt-8 border-t border-border pt-4 text-[10px] uppercase tracking-widest text-muted-foreground">
              Confidential · For internal city government use only
            </div>
          </GlassCard>
        </div>
      </div>
    </AppShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-6">
      <h3 className="font-display text-sm font-semibold uppercase tracking-widest text-primary">{title}</h3>
      <div className="mt-2 text-sm leading-relaxed text-foreground/90">{children}</div>
    </section>
  );
}
