/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CctvRouteImport } from './routes/cctv'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as FloodRouteImport } from './routes/flood'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as TransitRouteImport } from './routes/transit'
import { Route as ReportsExecutiveRouteImport } from './routes/reports.executive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CctvRoute = CctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const FloodRoute = FloodRouteImport.update({
  id: '/flood',
  path: '/flood',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitRoute = TransitRouteImport.update({
  id: '/transit',
  path: '/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExecutiveRoute = ReportsExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => ReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cctv': typeof CctvRoute
  '/citizen': typeof CitizenRoute
  '/copilot': typeof CopilotRoute
  '/flood': typeof FloodRoute
  '/map': typeof MapRoute
  '/replay': typeof ReplayRoute
  '/reports': typeof ReportsRouteWithChildren
  '/routing': typeof RoutingRoute
  '/signal': typeof SignalRoute
  '/simulate': typeof SimulateRoute
  '/transit': typeof TransitRoute
  '/reports/executive': typeof ReportsExecutiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cctv': typeof CctvRoute
  '/citizen': typeof CitizenRoute
  '/copilot': typeof CopilotRoute
  '/flood': typeof FloodRoute
  '/map': typeof MapRoute
  '/replay': typeof ReplayRoute
  '/reports': typeof ReportsRouteWithChildren
  '/routing': typeof RoutingRoute
  '/signal': typeof SignalRoute
  '/simulate': typeof SimulateRoute
  '/transit': typeof TransitRoute
  '/reports/executive': typeof ReportsExecutiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cctv': typeof CctvRoute
  '/citizen': typeof CitizenRoute
  '/copilot': typeof CopilotRoute
  '/flood': typeof FloodRoute
  '/map': typeof MapRoute
  '/replay': typeof ReplayRoute
  '/reports': typeof ReportsRouteWithChildren
  '/routing': typeof RoutingRoute
  '/signal': typeof SignalRoute
  '/simulate': typeof SimulateRoute
  '/transit': typeof TransitRoute
  '/reports/executive': typeof ReportsExecutiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/cctv'
    | '/citizen'
    | '/copilot'
    | '/flood'
    | '/map'
    | '/replay'
    | '/reports'
    | '/routing'
    | '/signal'
    | '/simulate'
    | '/transit'
    | '/reports/executive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/cctv'
    | '/citizen'
    | '/copilot'
    | '/flood'
    | '/map'
    | '/replay'
    | '/reports'
    | '/routing'
    | '/signal'
    | '/simulate'
    | '/transit'
    | '/reports/executive'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/cctv'
    | '/citizen'
    | '/copilot'
    | '/flood'
    | '/map'
    | '/replay'
    | '/reports'
    | '/routing'
    | '/signal'
    | '/simulate'
    | '/transit'
    | '/reports/executive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CctvRoute: typeof CctvRoute
  CitizenRoute: typeof CitizenRoute
  CopilotRoute: typeof CopilotRoute
  FloodRoute: typeof FloodRoute
  MapRoute: typeof MapRoute
  ReplayRoute: typeof ReplayRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  RoutingRoute: typeof RoutingRoute
  SignalRoute: typeof SignalRoute
  SimulateRoute: typeof SimulateRoute
  TransitRoute: typeof TransitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cctv': {
      id: '/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof CctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flood': {
      id: '/flood'
      path: '/flood'
      fullPath: '/flood'
      preLoaderRoute: typeof FloodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transit': {
      id: '/transit'
      path: '/transit'
      fullPath: '/transit'
      preLoaderRoute: typeof TransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/executive': {
      id: '/reports/executive'
      path: '/executive'
      fullPath: '/reports/executive'
      preLoaderRoute: typeof ReportsExecutiveRouteImport
      parentRoute: typeof ReportsRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsExecutiveRoute: typeof ReportsExecutiveRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsExecutiveRoute: ReportsExecutiveRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CctvRoute: CctvRoute,
  CitizenRoute: CitizenRoute,
  CopilotRoute: CopilotRoute,
  FloodRoute: FloodRoute,
  MapRoute: MapRoute,
  ReplayRoute: ReplayRoute,
  ReportsRoute: ReportsRouteWithChildren,
  RoutingRoute: RoutingRoute,
  SignalRoute: SignalRoute,
  SimulateRoute: SimulateRoute,
  TransitRoute: TransitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
